### ISSUE TITLE
Player Takes 100% of CPU

### ISSUE THREAD

**Issue by ndmerrill** [NathanMer/RFSMP#11]
The player uses as much processing power as it can. This is probably due to rendering the window way more times than necessary, but I'm not sure.

**Comment by tommy-mor** [comment]
I think it may be because the progress bar is rendered as fast as it can

**Comment by ndmerrill** [comment]
We should make it so it only renders when it changes length.

**Comment by tommy-mor** [comment]
well duh

**Comment by ndmerrill** [comment]
You should do it then.

**Comment by ndmerrill** [comment]
Also, you could fix #5 at the same time.

**Comment by ndmerrill** [comment]
I'm going to close this issue for now, although we may need to revisit it if #5 becomes an issue.
