### ISSUE TITLE
Fix Error Handling

### ISSUE THREAD

**Issue by ndmerrill** [NathanMer/RFSMP#9]
Right now, whenever something goes wrong, the code does something random. It either exits nicely, or it panics. Sometimes it doesn't even give an error message. We should make it do the same thing every time.

**Comment by tommy-mor** [comment]
Another error that must be handled is when it is passed a file that is not a song.

**Comment by ndmerrill** [comment]
This could use some more improvement, but is good enough for now. Closing.
